#!/usr/bin/env bash
# -*- mode: sh -*-
# vi: set ft=sh :

#Script para controlar todos los comando
#En desarrollo


DIR_PWD="$(pwd)"
DIR_SOURCE="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
. $DIR_SOURCE/bin/env.sh


